#!/bin/bash

set -Eeuo pipefail

cd "$(dirname "$0")"/..

set -x

[[ -d ~/.zest ]] || ln -s "$PWD" ~/.zest
mkdir -p ~/.config/systemd/user/
cp -f systemd/zest.service ~/.config/systemd/user/

systemctl enable --user zest
systemctl restart --user zest
systemctl status --user zest
